myproject/urls.py
from django.conf.urls import patterns, include, url
from filebrowser.sites import site
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from blog.sitemap import *
from tastypie.api import Api
from blog.api import PostResource, UserResource, CommentResource
from todo.api import TodoResoure

sitemaps = {
    "blog": BlogSitemap
}    
admin.autodiscover()
entry_resource = PostResource()
todo_resource = TodoResoure()
cm = CommentResource()
v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(PostResource())

urlpatterns = patterns('home.views',
       (r'^$', 'main'),
       
        )
urlpatterns += patterns('blog.views',
      (r'^blog$', 'main'),
      
        (r"^add_comment/(\d+)/$", "add_comment"),
        (r"^month/(\d+)/(\d+)/$", "month"),
        (r"^delete_comment/(\d+)/$", "delete_comment"),
        (r"^delete_comment/(\d+)/(\d+)/$", "delete_comment"),
        (r'^([\w-]+).html$', 'post'),
        (r'^tag/([\w-]+)$', 'tag'),
         (r'^category/([\w-]+)$', 'category'),
       (r'^demo/', 'demo'),
        )

urlpatterns += patterns('page.views',
        (r'^page$', 'main'),
        (r"^page/add_comment/(\d+)/$", "add_comment"),
        (r"^page/month/(\d+)/(\d+)/$", "month"),
        (r"^page/delete_comment/(\d+)/$", "delete_comment"),
        (r"^page/delete_comment/(\d+)/(\d+)/$", "delete_comment"),
        (r'^([\w-]+)$', 'post'),
      
        )
urlpatterns += patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^myproject/', include('myproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
     url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
     url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
     #url(r'^demo/','django.views.generic.simple.direct_to_template',{'template':'demo.html'}),
     url(r'^api/', include(v1_api.urls)),
     url(r'^cm/', include(cm.urls)),
     url(r'^shop/', 'book.views.index'),
     url(r'^comments/', include('django.contrib.comments.urls')),
     url(r'^contact/', include('quix.django.contact.urls')),   
     url(r'^todo/', include(todo_resource.urls)),
     url(r'^todolist/', 'todo.views.home', name='home'),
     #url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

blog/models.py
from django.db import models
from django.db.models import permalink
from django.conf.locale import sl
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
import os
from filebrowser.fields import FileBrowseField
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

  

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)

class Category(models.Model):
    title = models.CharField(max_length=80)
    slug = models.CharField(max_length=100,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    position = models.PositiveSmallIntegerField("Position")
    class Meta:
        ordering = ['position']
    def save(self, *args, **kwargs):
        if self.slug != "":
            super(Category, self).save(*args, **kwargs)
        else:
            self.slug = slugify(self.title)            
            super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title
    @permalink
    def get_absolute_url(self):
        return "/category/%s/" % self.slug   
class TaggedPost(TaggedItemBase):
    content_object = models.ForeignKey('Post')  
      
class Post(models.Model):
    title = models.CharField(max_length=80)
    slug = models.CharField(max_length=100,blank=True)
    thumbnail = FileBrowseField("Image", max_length=200, blank=True, null=True)
    user = models.ForeignKey(User)
    category = models.ManyToManyField(Category)
    content = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager(through=TaggedPost)
    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "title__icontains","category__icontains")
    def save(self, *args, **kwargs):
                            
        if self.slug != "":
            super(Post, self).save(*args, **kwargs)
        else:
            self.slug = slugify(self.title)            
            super(Post, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title
    @permalink
    def get_absolute_url(self):
        return "/%s.html" % self.slug 

class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)
    def __unicode__(self):
        return u"%s: %s" % (self.post, self.body[:60])  
    
class Image(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    image = FileBrowseField("Image", max_length=200, blank=True, null=True)
    position = models.PositiveSmallIntegerField("Position")
    post = models.ForeignKey(Post)
    class Meta:
        ordering = ['position']
    def __unicode__(self):
        return u"%s" % (self.image)  

blog/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from blog.models import *
from django.shortcuts import render_to_response
from django.forms import ModelForm
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect
import time
from calendar import month_name
from tinymce.widgets import TinyMCE
from django.template.context import RequestContext
def main(request):
    """Main listing."""
    posts = Post.objects.all().order_by("-created")
    categories = Category.objects.all().order_by("title")
    paginator = Paginator(posts, 10)
  
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("blog/list.html", dict(posts=posts, user=request.user,categories=categories,
                                            post_list=posts.object_list, months=mkmonth_lst()))

def category(request, slug):
    """Main listing."""
    category = Category.objects.get(slug=slug)
    categories = Category.objects.all().order_by("title")
    posts = Post.objects.filter(category=category).order_by("-created")
    paginator = Paginator(posts, 10)
  
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("blog/list.html", dict(posts=posts,request=request,categories=categories, user=request.user,
                                            post_list=posts.object_list, months=mkmonth_lst()))

def post(request, slug):
    """Single post with comments and a comment form."""
    post = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post=post)
    relatedposts = Post.objects.filter(tags__name__in=[post.tags.all])
    d = dict(post=post, comments=comments,form=CommentForm(),request=request, user=request.user, relatedposts=relatedposts)
    d.update(csrf(request))
    return render_to_response("blog/post.html", d)

def tag(request, slug):
    """Single post with comments and a comment form."""
    categories = Category.objects.all().order_by("title")
    posts = Post.objects.filter(tags__slug__in=[slug])
    d = dict(posts=posts, form=CommentForm(),categories=categories, user=request.user,slug=slug)
    d.update(csrf(request))
    return render_to_response("blog/list.html", d)

def demo(request):
    """Main listing."""
   
    log = False
    if request.user.is_staff:
        log = True 
   

    return render_to_response("demo.html", dict(logged = log))


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ["post"]

def add_comment(request, pk):
    """Add a new comment."""
    p = request.POST

    if p.has_key("body") and p["body"]:
        author = "Anonymous"
        if p["author"]: author = p["author"]

        comment = Comment(post=Post.objects.get(pk=pk))
        cf = CommentForm(p, instance=comment)
        cf.fields["author"].required = False
        post=Post.objects.get(pk=pk)
        slug = post.slug
        comment = cf.save(commit=False)
        comment.author = author
        comment.save()
    return HttpResponseRedirect(reverse("blog.views.post", args=[slug]))

def mkmonth_lst():
    """Make a list of months to show archive links."""

    if not Post.objects.count(): return []

    # set up vars
    year, month = time.localtime()[:2]
    first = Post.objects.order_by("created")[0]
    fyear = first.created.year
    fmonth = first.created.month
    months = []

    # loop over years and months
    for y in range(year, fyear - 1, -1):
        start, end = 12, 0
        if y == year: start = month
        if y == fyear: end = fmonth - 1

        for m in range(start, end, -1):
            months.append((y, m, month_name[m]))
    return months

def month(request, year, month):
    """Monthly archive."""
    posts = Post.objects.filter(created__year=year, created__month=month)
    return render_to_response("blog/list.html", dict(post_list=posts, user=request.user,
                                                months=mkmonth_lst(), archive=True))

def delete_comment(request, post_pk, pk=None):
    """Delete comment(s) with primary key `pk` or with pks in POST."""
    if request.user.is_staff:
        if not pk: pklst = request.POST.getlist("delete")
        else: pklst = [pk]

        for pk in pklst:
            Comment.objects.get(pk=pk).delete()
        return HttpResponseRedirect(reverse("blog.views.post", args=[post_pk]))
    

templates/blog/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head> <title>{% block title %}{% if post.title %}{{post.title}}{% else %} My Blog{% endif %}{% endblock %}</title> </head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
                <h3>MyBlog</h3>
                {% if user.is_staff %}
                <a href="{% url admin:index %}">Admin</a>
                <a href="{% url admin:blog_post_add %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

templates/blog/list.html
{% extends "base.html" %}
{% block content %}
{% load fb_versions %}
<div class="one">

	<div class="inner-content">
		{% for post in posts %}
		<div class="post-entry">
			<div class="post-date">
				<span class="post-month">{{ post.created.month }}</span>
				<strong class="post-day">{{ post.created.day }}</strong>
				<span class="post-year ">{{ post.created.year }}</span>
			</div>
			<div class="post-intro">
				<a href="{% url blog.views.post post.slug %}"><h3> {{ post.title }}</h3></a>

				<p>
					{% if post.image_set.all %}
					<img src="/media/{{post.image_set.all|first}}" alt=" " width="615" height="175" class="img-align-left">
				    
					
					{% else %}
					<img src="{% version post.thumbnail 'big' %}" alt=" " width="615" height="175" class="img-align-left">
				    {% endif %}
				</p>

				<p>
					{{ post.content|striptags|truncatewords:"100" }}
				</p>

				<p>
					<a href="{% url blog.views.post post.slug %}" class="button small round grey">Read More</a>
				</p>

			</div>
			<div class="horizontal-line"></div>
		</div>

		{% endfor %}

		<!-- Next/Prev page links  -->
		{% if posts.object_list and posts.paginator.num_pages > 1 %}
		<ul class="blog-pagination">
			<li>
				{% if posts.has_previous %} <a href= "?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a> {% endif %}

			<li class="active">
				&nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
			</li>
			{% if posts.has_next %}
			<li>
				<a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a> {% endif %}
			</li>
		</ul>
		{% endif %}

	</div>

	<div class="one-fourth last">

		<h4>Category</h4>
		<ul class="simple-nav">
			<!--SIMPLE UL -->
			
			{% for category in categories %}
			<li class="">
				<a href="{% url blog.views.category category.slug %}">{{ category.title }}</a>
			</li>
			{% endfor %}
		</ul>
		<div class="horizontal-line"></div>

	</div>
</div>

{% endblock %}

{% for comment in post.comment_set.all %}
<div class="comment">
	<div class="time">
		{{ comment.created }} | {{ comment.author }}
	</div>
	<div class="body">
		{{ comment.body|linebreaks }}
	</div>
	{% if user.is_staff %}
	<input type="checkbox" name="delete" value="{{ comment.pk }}">
	<a href="{% url 'blog.views.delete_comment' post.pk comment.id %}">delete</a>
	{% endif %}
</div>
{% endfor %}

templates/blog/post.html
{% extends "base.html" %}
{% block content %}
{% load fb_versions %}
<div class="one">
	<div class="inner-content">

		<div class="post-entry">
			<div class="post-date">
				<span class="post-month">{{ post.created.month }}</span>
				<strong class="post-day">{{ post.created.day }}</strong>
				<span class="post-year ">{{ post.created.year }}</span>
			</div>
			<div class="post-intro">
				<a href="{% url blog.views.post post.slug %}"><h3> {{ post.title }}</h3></a>
<ul>
{%for image in post.image_set.all %}
<li><a href="/media/{{image}}" rel="prettyPhoto"><img src="{% version image 'thumbnail' %}" /></a></li>

{% endfor %}
	</ul>	
	
	{{request.path}}
	
		<p>
					{{ post.content|safe }}
				</p>

			</div>
			<div class="horizontal-line"></div>
		</div>
<h3>Related Posts:</h3>
<ul>
	{% for post in post.tags.similar_objects %}
	<li><a href="{% url blog.views.post post.slug %}">{{ post.title }}</a>	
			</li>
	{% endfor %}
</ul>

<h3>Tags:</h3>
{% for tag in post.tags.all %}
<a href="{% url blog.views.tag tag.slug %}">{{ tag.name }}</a>,
{% endfor %}
		<!-- {% for comment in comments %}

		<div class="inner-content">
		<div class="comment-area">
		<h4><a href="#">{{ comment.author|upper  }}</a> <span class="italic-crim">{{ comment.created }}</span></h4>
		<p>{{ comment.body|linebreaks }}</p>

		</div>
		<div class="horizontal-line"></div>
		</div>

		{% endfor %}

		</form>

		{% if comments %}<strong>LEAVE A COMMENT</strong>{% endif %}
		<p>
		</p>
		<form action="{% url blog.views.add_comment post.id %}" method="POST">{% csrf_token %}
		<div id="cform">

		<fieldset>
		<label><strong>Name</strong> <span class="required">*</span></label>
		{{ form.author }}
		</fieldset>

		<fieldset>
		<label><strong>Your Comment</strong> <span class="required">*</span></label>
		{{ form.body|linebreaks }}
		</fieldset>

		</div>
		<div id="submit"><input type="submit" value="Submit"></div>
		</form> -->

		<!--END form ID contact_form-->

		{% load comments i18n %}
		{% get_comment_count for blog.post post.id as comment_count %}

		<p>
			This post has {{ comment_count }} comments.
		</p>
		{% get_comment_list for blog.post post.id as comment_list %}
		{% for comment in comment_list %}
		<div class="inner-content">
		<div class="comment-area">
		<h4><a href="#">{{ comment.user_name|upper  }}</a> <span class="italic-crim">{{ comment.submit_date }}</span></h4>
		<p>{{ comment.comment|linebreaks }}</p>

		</div>
		<div class="horizontal-line"></div>
		</div>
		{% endfor %}
		{% load tags %}
		
		{% get_comment_form for blog.post post.id as form %}

		<table>

			<form action="{% comment_form_target %}" method="POST">
				{% csrf_token %}
				{{ form }}
				<tr>
					<td colspan="2">
						
						<input type="hidden" name="next" value="{% url blog.views.post post.slug %}" />
					<input type="submit" name="submit" value="Post">
					<input type="submit" name="preview" value="Preview">
					</td>
				</tr>
			</form>
		</table>
	</div>

		{% include "right_sidebar.html" %}
</div>

{% endblock %}